### ISSUE TITLE
Change refification/refify misspelling to reification/reify

### ISSUE THREAD

**Issue by antoni-devlin** [romansky/dom-to-semantic-markdown#3]
Should refification/refify be reification/reify instead? I searched npm for [reification](https://www.npmjs.com/search?q=reification) and [refification](https://www.npmjs.com/search?q=refification) as a sense check.

If so, it looks like [5 files](https://github.com/search?q=repo%3Aromansky%2Fdom-to-semantic-markdown%20%22refify%22&type=code) are affected by the misspelling.

**Comment by romansky** [comment]
Hi @antoni-devlin,

Thank you for pointing that out! You are correct in identifying the potential misspelling. However, the term “refification” is actually intentional in this context.

The feature converts links like “https://www.google.com” into “ref1”, effectively turning them into “refs” or “refifying” them. This is distinct from “reification,” which has a different meaning.

Let me know if you need any further assistance!

**Comment by antoni-devlin** [comment]
Ah, sound logic, my mistake!
